### ISSUE TITLE
Question: handling untrusted data?

### ISSUE THREAD

**Issue by dpc** [yasammez/nachricht#1]
One important property of serialization formats is how do they handle untrusted data? What is the worst thing that can happen if I was to deserialize a message from potentially malicious actors.

**Comment by yasammez** [comment]
The format of nachricht allows for messages to be arbitrarily large. So I suspect the worst thing could be an OOM attack on the deserializer, given that attacker, network and victim's network buffers are large enough. In practice I would suppose that other parts of the stack already enforce size limits. If this is not the case, you should probably check the size yourself before attempting to deserialize.

Apart from that the deserializer should never panic or even segfault. This has, however, not been thoroughly proven yet. Fuzzing would be nice if I'll ever get around to do it properly.

**Comment by dpc** [comment]
What waould be the easiest way to to check the size of the incoming data? Where exactly do I plug it in and how? If the attacker set a huge lenght, is it going to basically crash the process the moment the deserializer code attempts to alloc memory for it?

**Comment by yasammez** [comment]
Now that I think of it, a malformed message which announces a container of size `u64::MAX` (which doesn't even need to exist, the message can end with the header) will probably crash immediately. The deserializer should switch to fallible allocations and return a proper error if there isn't enough memory to handle a message. Thank you for bringing this to my attention. I'll keep this issue open until I implement this.

_Edit:_ This is exactly what's happening:
```
echo -en "\x7f\xff\xff\xff\xff\xff\xff\xff\xff" | nq
thread 'main' panicked at 'capacity overflow', library\alloc\src\raw_vec.rs:537:5
```

**Comment by dpc** [comment]
Yeah. This is not uncommon in serialization formats, and usually there's either some way to mitigate it (like you mentioned; could be something as simple as a maximum deserialized data size setting, and deserializer tracking already allocated size of the whole doucment) or just more or less explicitly the format is supposed to be used to exchange internal and thus trusted data. But even then it's good to have some maximum.

**Comment by yasammez** [comment]
In RION, instead of the amount of elements, the size in bytes of a container is encoded. This makes it trivial to check the validity of a message: just check if there are enough bytes left in the buffer. However I didn't like that approach because it compliactes encoding and you cannot pre-allocate a vector when encountering a container because you don't know how many elements it will contain. I've built in a rather hacky solution while waiting for https://github.com/rust-lang/rust/issues/48043 to stabilize. Version 0.2.0 now behaves like this:

```bash
echo -en "\x7f\xff\xff\xff\xff\ff\xff\xff\xff" | nq
Error: An allocation for 18446744069622661119 x 72 bytes failed at input position 9

Caused by:
    An allocation for 18446744069622661119 x 72 bytes failed
```

This at least prevents the panic which I really didn't like. Thanks again for making me notice this. However, the absence of one bug says nothing about all other possible bugs so fuzzing would still be a really good idea :-)
